Repository AY2021S1-CS2113T-F14-4/tp, pull requests merged in 2020-10, with the labels that each got.

#83 added clearcommand diagram & description for help command
  docs/DeveloperGuide.md
  docs/diagrams/ClearCommand.png
  docs/diagrams/HelpCommand.png
Labels: documentation

#86 Linebreaker
  docs/DeveloperGuide.md
Labels: documentation

#89 Duration of class and personalEvent
  src/main/java/command/AddCommand.java
  src/main/java/command/EditCommand.java
  src/main/java/event/Assignment.java
  src/main/java/event/Class.java
  src/main/java/event/Event.java
  src/main/java/event/PersonalEvent.java
  src/main/java/eventlist/EventList.java
  src/main/java/exception/EndBeforeStartEventException.java
  src/main/java/exception/NoEndTimeClassException.java
  src/main/java/exception/NoEventLocationException.java
  src/main/java/location/OnlineLocation.java
  src/main/java/parser/Parser.java
  src/main/java/storage/Storage.java
  src/main/java/ui/UI.java
  src/test/java/command/AddCommandTest.java
Labels: priority.High, task

#91 User info
  .gitignore
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/NuSchedule.java
  src/main/java/command/SortCommand.java
  src/main/java/command/UserInfoCommand.java
  src/main/java/parser/Parser.java
  src/main/java/storage/Storage.java
  src/main/java/ui/UI.java
  src/main/java/usercommunication/UserInfo.java
  src/main/java/usercommunication/UserType.java
  src/test/java/command/EditCommandTest.java
Labels: priority.Medium, task
