Repository AY2021S1-CS2113T-F14-4/tp, pull requests merged in 2020-11, with the labels that each got.

#159 Repeat Command
  src/main/java/command/RepeatCommand.java
  src/main/java/event/Assignment.java
  src/main/java/event/Class.java
  src/main/java/event/Event.java
  src/main/java/event/PersonalEvent.java
  src/main/java/event/SelfStudy.java
  src/main/java/eventlist/EventList.java
  src/main/java/exception/EmptyRepeatException.java
  src/main/java/exception/InvalidNumWeekException.java
  src/main/java/exception/NoClassWeekException.java
  src/main/java/exception/NoRepeatWeekException.java
  src/main/java/exception/RepeatIndexFormatException.java
  src/main/java/parser/Parser.java
  src/main/java/storage/Storage.java
  src/main/java/ui/UI.java
Labels: priority.High, task

#169 Documentation
  docs/UserGuide.md
  docs/team/max-wunan.md
Labels: documentation

#174 Print area locations
  docs/team/Lee-Juntong.md
  src/main/java/command/PrintAreaLocationsCommand.java
  src/main/java/parser/Parser.java
Labels: priority.High, task

#175 Documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AutoClearCommand.png
  docs/diagrams/ClearBeforeCommand.png
  docs/diagrams/ClearCommand.png
  docs/diagrams/HelpCommand.png
Labels: documentation

#182 Enhance auto clear
  docs/team/Lee-Juntong.md
  src/main/java/NuSchedule.java
  src/main/java/command/AddCommand.java
  src/main/java/command/AutoClearCommand.java
  src/main/java/command/ClearBeforeCommand.java
  src/main/java/command/ClearCommand.java
  src/main/java/command/Command.java
  src/main/java/command/DeleteCommand.java
  src/main/java/command/DoneCommand.java
  src/main/java/command/EditCommand.java
  src/main/java/command/ExitCommand.java
  src/main/java/command/FindCommand.java
  src/main/java/command/FindDateCommand.java
  src/main/java/command/HelpCommand.java
  src/main/java/command/LocateCommand.java
  src/main/java/command/PrintAreaLocationsCommand.java
  src/main/java/command/PrintFullListCommand.java
  src/main/java/command/PrintLocationCommand.java
  src/main/java/command/ReminderCommand.java
  src/main/java/command/RepeatCommand.java
  src/main/java/command/SortCommand.java
  src/main/java/command/StudyTimeCommand.java
  src/main/java/command/UserInfoCommand.java
  src/main/java/eventlist/EventList.java
  src/main/java/exception/WrongAutoClearArgumentException.java
  src/main/java/parser/Parser.java
  src/main/java/storage/Storage.java
  src/main/java/ui/UI.java
  src/main/java/usercommunication/UserInfo.java
  src/test/java/command/EditCommandTest.java
Labels: priority.Medium, task
